### PR TITLE
bootanimation: Fix looping issue

### PR DESCRIPTION
**Pull request by enesykaya**

### CODE REVIEW

**Comment by gotenksIN** [comment]
I haven't had this for months now :think:

**Comment by enesykaya** [comment]
> I haven't had this for months now :think:

This still happens only at first boot for me :(

**Comment by idoybh** [comment]
> I haven't had this for months now :think:

Same here
Heck even had bootloops... It stays on the final y forever

**Comment by gotenksIN** [comment]
will let ahmed review this whenever he's back

**Comment by Lacentix** [comment]
Could you elaborate more? what kind of looping do you face? Send a video if you can as well.
Thanks in advance

**Comment by enesykaya** [comment]
> Could you elaborate more? what kind of looping do you face? Send a video if you can as well.
> Thanks in advance

Boot animation finishes too early so screen goes black till the device boots as you can see in the video.

https://drive.google.com/file/d/1XO2TMf6xbDFG7i5oilBjl8BYM6hqCgP4/view?usp=sharing

**Comment by ALKALiKong233** [comment]
> > Could you elaborate more? what kind of looping do you face? Send a video if you can as well.
> > Thanks in advance
> 
> Boot animation finishes too early so screen goes black till the device boots as you can see in the video.
> 
> https://drive.google.com/file/d/1XO2TMf6xbDFG7i5oilBjl8BYM6hqCgP4/view?usp=sharing

Same thing happened on dipper too after updating it took a long time to boot and after the bootanimation running off screen goes black till the device boot

**Comment by idoybh** [comment]
Do you use the same resolution @ALKALiKong233 @enesykaya ? If so wait for @Lacentix to fix. Closing for now until he gets this sorted out. Welcome to continue conversing here or over tg.

**Comment by gotenksIN** [comment]
both of them use 1080p just like me

**Comment by idoybh** [comment]
> both of them use 1080p just like me

And it works fine for you right?

**Comment by gotenksIN** [comment]
yep
automatically fixed about 2 months ago

**Pull request closed without merging**
